# Generated by Django 5.1.3 on 2024-11-21 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Atividade',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('criador_id', models.IntegerField(db_column='criador_id')),
                ('adicionais', models.TextField(db_column='adicionais')),
                ('data', models.DateField(db_column='data')),
                ('hora', models.TimeField(db_column='hora')),
            ],
            options={
                'db_table': 'Atividade',
                'ordering': ['id'],
                'managed': True,
            },
        ),
    ]
