# Generated by Django 5.1.3 on 2024-11-29 01:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('psiuApiApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Carona',
            fields=[
                ('atividade_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='psiuApiApp.atividade')),
                ('local_saida', models.TimeField(db_column='local_saida')),
            ],
            options={
                'db_table': 'Carona',
                'ordering': ['local_saida'],
                'managed': True,
            },
            bases=('psiuApiApp.atividade',),
        ),
    ]
