# Generated by Django 5.1.3 on 2024-11-30 15:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('psiuApiApp', '0003_atividade_tipo_atividade'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConhecerPessoas',
            fields=[
                ('atividade_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='psiuApiApp.atividade')),
                ('atividade', models.TextField(db_column='atividade')),
                ('local', models.TextField(db_column='local')),
            ],
            options={
                'db_table': 'ConhecerPessoas',
                'ordering': ['atividade'],
                'managed': True,
            },
            bases=('psiuApiApp.atividade',),
        ),
        migrations.CreateModel(
            name='Estudos',
            fields=[
                ('atividade_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='psiuApiApp.atividade')),
                ('materia', models.TextField(db_column='materia')),
                ('local', models.TextField(db_column='local')),
            ],
            options={
                'db_table': 'Estudos',
                'ordering': ['materia'],
                'managed': True,
            },
            bases=('psiuApiApp.atividade',),
        ),
        migrations.CreateModel(
            name='Extracurriculares',
            fields=[
                ('atividade_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='psiuApiApp.atividade')),
                ('atividade', models.TextField(db_column='atividade')),
                ('local', models.TextField(db_column='local')),
            ],
            options={
                'db_table': 'Extracurriculares',
                'ordering': ['atividade'],
                'managed': True,
            },
            bases=('psiuApiApp.atividade',),
        ),
        migrations.CreateModel(
            name='Liga',
            fields=[
                ('atividade_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='psiuApiApp.atividade')),
                ('nome', models.TextField(db_column='nome')),
                ('local', models.TextField(db_column='local')),
            ],
            options={
                'db_table': 'Liga',
                'ordering': ['nome'],
                'managed': True,
            },
            bases=('psiuApiApp.atividade',),
        ),
        migrations.AlterModelOptions(
            name='carona',
            options={'managed': True, 'ordering': ['local_chegada']},
        ),
        migrations.AddField(
            model_name='carona',
            name='local_chegada',
            field=models.TextField(db_column='local_chegada', default='Nada'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='carona',
            name='local_saida',
            field=models.TextField(db_column='local_saida'),
        ),
    ]
