# Generated by Django 5.1.3 on 2024-11-30 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('psiuApiApp', '0005_alter_atividade_criador_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='atividade',
            name='vagas',
            field=models.PositiveIntegerField(db_column='vagas', default=4),
        ),
        migrations.AlterField(
            model_name='atividade',
            name='adicionais',
            field=models.TextField(blank=True, db_column='adicionais'),
        ),
    ]
