# Generated by Django 5.1.3 on 2024-11-30 21:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('psiuApiApp', '0006_atividade_vagas_alter_atividade_adicionais'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParticipaAtividade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario', models.TextField(db_column='usuario')),
                ('atividade', models.ForeignKey(db_column='atividade', on_delete=django.db.models.deletion.CASCADE, to='psiuApiApp.atividade')),
            ],
            options={
                'db_table': 'ParticipaAtividade',
                'ordering': ['atividade'],
                'managed': True,
            },
        ),
    ]
